stages:
  - prepare
  - build_and_test
  - run
  - logs

base-image-build:
  stage: prepare
  tags:
    - car-wash-owner-panel
  only:
    - master
  script:
    - echo "build base docker image ..."
    - docker image build . --build-arg HTTP_PORT=80 -t car_wash_frontend_base_img -f DockerfileBase

base-image-test:
  stage: build_and_test
  tags:
    - car-wash-owner-panel
  only:
    - master
  script:
    - echo "test base docker image ..."
    - docker run -i --rm --name car_wash_frontend_test car_wash_frontend_base_img npm run test

nginx-image-build:
  stage: build_and_test
  tags:
    - car-wash-owner-panel
  only:
    - master
  script:
    - echo "build nginx docker image ..."
    - docker image build . --build-arg "HTTP_PORT=80" -t car_wash_frontend_img

run-nginx-server:
  stage: run
  tags:
    - car-wash-owner-panel
  only:
    - master
  script:
    - echo "stop docker container ..."
    - if [ "$( docker container inspect -f '{{.State.Running}}' car_wash_frontend_cntr )" == "true" ]; then docker stop car_wash_frontend_cntr; fi
    - echo "remove docker container ..."
    - if [ "$( docker container inspect -f '{{.Name}}' car_wash_frontend_cntr )" == "/car_wash_frontend_cntr" ]; then docker rm car_wash_frontend_cntr; fi
    - echo "create and run docker container ..."
    - >
      docker run
      -d
      -p 80:80
      --env HTTP_PORT=80
      --name car_wash_frontend_cntr
      car_wash_frontend_img

test-startup-logs:
  stage: logs
  tags:
    - car-wash-owner-panel
  only:
    - master
  script:
    - sleep 30
    - docker logs car_wash_frontend_cntr 2>errors.log
    - cat ./errors.log
    - if [ "$(stat --format=%s './errors.log')" != "0" ]; then exit 1; fi
